spring.application.name=medivibe
#Configuration for database connection
spring.datasource.url=jdbc:mysql://localhost:3306/MedVibedb
spring.datasource.username=root
spring.datasource.password=teste

#Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server configuration
server.port=9090

